# Import the required libraries

In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Import the dataset

In [34]:
dataset = pd.read_csv("ai_job_market.csv")

In [35]:
dataset.head()

,job_id,company_name,industry,job_title,skills_required,experience_level,employment_type,location,salary_range_usd,posted_date,company_size,tools_preferred
0,1,Foster and Sons,Healthcare,Data Analyst,"NumPy, Reinforcement Learning, PyTorch, Scikit...",Mid,Full-time,"Tracybury, AR",92860-109598,2025-08-20,Large,"KDB+, LangChain"
1,2,"Boyd, Myers and Ramirez",Tech,Computer Vision Engineer,"Scikit-learn, CUDA, SQL, Pandas",Senior,Full-time,"Lake Scott, CU",78523-144875,2024-03-22,Large,"FastAPI, KDB+, TensorFlow"
2,3,King Inc,Tech,Quant Researcher,"MLflow, FastAPI, Azure, PyTorch, SQL, GCP",Entry,Full-time,"East Paige, CM",124496-217204,2025-09-18,Large,"BigQuery, PyTorch, Scikit-learn"
3,4,"Cooper, Archer and Lynch",Tech,AI Product Manager,"Scikit-learn, C++, Pandas, LangChain, AWS, R",Mid,Full-time,"Perezview, FI",50908-123743,2024-05-08,Large,"TensorFlow, BigQuery, MLflow"
4,5,Hall LLC,Finance,Data Scientist,"Excel, Keras, SQL, Hugging Face",Senior,Contract,"North Desireeland, NE",98694-135413,2025-02-24,Large,"PyTorch, LangChain"

In [36]:
dataset.shape

(2000, 12)

In [37]:
dataset.isnull().sum()

job_id              0
company_name        0
industry            0
job_title           0
skills_required     0
experience_level    0
employment_type     0
location            0
salary_range_usd    0
posted_date         0
company_size        0
tools_preferred     0
dtype: int64

In [38]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   job_id            2000 non-null   int64
 1   company_name      2000 non-null   object
 2   industry          2000 non-null   object
 3   job_title         2000 non-null   object
 4   skills_required   2000 non-null   object
 5   experience_level  2000 non-null   object
 6   employment_type   2000 non-null   object
 7   location          2000 non-null   object
 8   salary_range_usd  2000 non-null   object
 9   posted_date       2000 non-null   object
 10  company_size      2000 non-null   object
 11  tools_preferred   2000 non-null   object
dtypes: int64(1), object(11)
memory usage: 187.6+ KB

In [39]:
dataset.describe

<bound method NDFrame.describe of       job_id                   company_name    industry  \
0          1                Foster and Sons  Healthcare
1          2        Boyd, Myers and Ramirez        Tech
2          3                       King Inc        Tech
3          4       Cooper, Archer and Lynch        Tech
4          5                       Hall LLC     Finance
...      ...                            ...         ...
1995    1996       Mueller, Ellis and Clark     Finance
1996    1997                     Roberts-Yu  Automotive
1997    1998  Brooks, Williams and Randolph   Education
1998    1999                Castaneda-Smith   Education
1999    2000                    Estes Group     Finance

                     job_title  \
0                 Data Analyst
1     Computer Vision Engineer
2             Quant Researcher
3           AI Product Manager
4               Data Scientist
...                        ...
1995              NLP Engineer
1996        AI Product Manager
1997              Data Analyst
1998          Quant Researcher
1999          Quant Researcher

                                        skills_required experience_level  \
0     NumPy, Reinforcement Learning, PyTorch, Scikit...              Mid
1                       Scikit-learn, CUDA, SQL, Pandas           Senior
2             MLflow, FastAPI, Azure, PyTorch, SQL, GCP            Entry
3          Scikit-learn, C++, Pandas, LangChain, AWS, R              Mid
4                       Excel, Keras, SQL, Hugging Face           Senior
...                                                 ...              ...
1995                           Flask, FastAPI, Power BI           Senior
1996           R, Flask, Excel, C++, CUDA, Scikit-learn              Mid
1997       Hugging Face, Excel, Scikit-learn, R, MLflow            Entry
1998                          AWS, Python, Scikit-learn           Senior
1999                        Flask, TensorFlow, Power BI           Senior

     employment_type                location salary_range_usd posted_date  \
0          Full-time           Tracybury, AR     92860-109598  2025-08-20
1          Full-time          Lake Scott, CU     78523-144875  2024-03-22
2          Full-time          East Paige, CM    124496-217204  2025-09-18
3          Full-time           Perezview, FI     50908-123743  2024-05-08
4           Contract   North Desireeland, NE     98694-135413  2025-02-24
...              ...                     ...              ...         ...
1995      Internship     Washingtonmouth, SD     90382-110126  2024-04-22
1996          Remote          Joshuafort, ZA     47848-137195  2023-12-02
1997        Contract  West Brittanyburgh, CG    134994-180108  2023-10-29
1998        Contract        Anthonyshire, OM      62388-82539  2024-08-10
1999       Full-time        Benjaminview, NE      55835-97374  2025-02-20

     company_size                  tools_preferred
0           Large                  KDB+, LangChain
1           Large        FastAPI, KDB+, TensorFlow
2           Large  BigQuery, PyTorch, Scikit-learn
3           Large     TensorFlow, BigQuery, MLflow
4           Large               PyTorch, LangChain
...           ...                              ...
1995        Large                           MLflow
1996        Large          KDB+, LangChain, MLflow
1997        Large                          PyTorch
1998        Large      MLflow, TensorFlow, FastAPI
1999      Startup                           MLflow

[2000 rows x 12 columns]>

In [40]:
dataset.value_counts("industry")

industry
Automotive    300
Education     294
Retail        293
E-commerce    291
Finance       279
Tech          274
Healthcare    269
Name: count, dtype: int64

In [41]:
dataset.value_counts("job_title")

job_title
Data Analyst                271
NLP Engineer                265
AI Product Manager          258
Quant Researcher            251
ML Engineer                 250
Data Scientist              238
AI Researcher               237
Computer Vision Engineer    230
Name: count, dtype: int64

In [42]:
dataset.duplicated().sum()

0

# Data Preprocessing

In [44]:
dataset.head(10)

,job_id,company_name,industry,job_title,skills_required,experience_level,employment_type,location,salary_range_usd,posted_date,company_size,tools_preferred
0,1,Foster and Sons,Healthcare,Data Analyst,"NumPy, Reinforcement Learning, PyTorch, Scikit...",Mid,Full-time,"Tracybury, AR",92860-109598,2025-08-20,Large,"KDB+, LangChain"
1,2,"Boyd, Myers and Ramirez",Tech,Computer Vision Engineer,"Scikit-learn, CUDA, SQL, Pandas",Senior,Full-time,"Lake Scott, CU",78523-144875,2024-03-22,Large,"FastAPI, KDB+, TensorFlow"
2,3,King Inc,Tech,Quant Researcher,"MLflow, FastAPI, Azure, PyTorch, SQL, GCP",Entry,Full-time,"East Paige, CM",124496-217204,2025-09-18,Large,"BigQuery, PyTorch, Scikit-learn"
3,4,"Cooper, Archer and Lynch",Tech,AI Product Manager,"Scikit-learn, C++, Pandas, LangChain, AWS, R",Mid,Full-time,"Perezview, FI",50908-123743,2024-05-08,Large,"TensorFlow, BigQuery, MLflow"
4,5,Hall LLC,Finance,Data Scientist,"Excel, Keras, SQL, Hugging Face",Senior,Contract,"North Desireeland, NE",98694-135413,2025-02-24,Large,"PyTorch, LangChain"
5,6,Ellis PLC,E-commerce,AI Product Manager,"GCP, Excel, Scikit-learn, MLflow",Senior,Remote,"South Kevin, TZ",92632-180718,2025-08-07,Large,"PyTorch, TensorFlow, FastAPI"
6,7,Matthews-Moses,Automotive,Data Analyst,"Python, Flask, Scikit-learn, GCP",Mid,Full-time,"West Shawn, LR",70575-88594,2024-12-23,Large,"PyTorch, MLflow"
7,8,Mullins Ltd,Education,Data Scientist,"Excel, SQL, Flask",Entry,Internship,"Port Hailey, RU",63032-82144,2024-08-14,Large,BigQuery
8,9,Aguilar PLC,Healthcare,ML Engineer,"Pandas, LangChain, GCP, Azure",Entry,Internship,"Butlermouth, GB",134239-188504,2025-09-15,Large,"Scikit-learn, LangChain, BigQuery"
9,10,Parks LLC,Automotive,Computer Vision Engineer,"Excel, Reinforcement Learning, TensorFlow",Senior,Full-time,"Nicoleshire, BA",79361-165029,2025-08-07,Large,"MLflow, TensorFlow"

In [45]:
dataset = dataset.dropna(subset=['job_title', 'skills_required', 'experience_level', 'industry', 'employment_type', 'company_size'])

* for skills_required column

In [47]:
from sklearn.preprocessing import MultiLabelBinarizer

In [48]:
skills_series = dataset['skills_required'].str.split(', ').explode().str.strip()
unique_skills_list = skills_series.value_counts().index.tolist()

In [49]:
mlb = MultiLabelBinarizer(classes=unique_skills_list)
skills_matrix = mlb.fit_transform(dataset['skills_required'].apply(lambda x: [s.strip() for s in str(x).split(',')]))
dataset['skills_array'] = skills_matrix.tolist()

In [50]:
skills_mapping = mlb.classes_.tolist()
print(skills_mapping)

['TensorFlow', 'Excel', 'Pandas', 'FastAPI', 'NumPy', 'Reinforcement Learning', 'Azure', 'Hugging Face', 'SQL', 'Keras', 'AWS', 'Power BI', 'GCP', 'Python', 'LangChain', 'PyTorch', 'Scikit-learn', 'Flask', 'CUDA', 'R', 'C++', 'MLflow']

In [51]:
row_1 = dataset.iloc[1]
print(f"Skills Array:{row_1['skills_array']}")

Skills Array:[0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0]

* for experience_level column

In [53]:
dataset.value_counts("experience_level")

experience_level
Entry     702
Mid       668
Senior    630
Name: count, dtype: int64

In [54]:
from sklearn.preprocessing import LabelBinarizer

In [55]:
lb_exp = LabelBinarizer()
exp_matrix = lb_exp.fit_transform(dataset['experience_level'])
dataset['experience_array'] = exp_matrix.tolist()

In [56]:
exp_mapping = lb_exp.classes_.tolist()
print(exp_mapping)

['Entry', 'Mid', 'Senior']

In [57]:
row_1 = dataset.iloc[1]
print(f"Experience Array:{row_1['experience_array']}")

Experience Array:[0, 0, 1]

* for industry column

In [59]:
dataset.value_counts("industry")

industry
Automotive    300
Education     294
Retail        293
E-commerce    291
Finance       279
Tech          274
Healthcare    269
Name: count, dtype: int64

In [60]:
lb_ind = LabelBinarizer()
ind_matrix = lb_ind.fit_transform(dataset['industry'])
dataset['industry_array'] = ind_matrix.tolist()

In [61]:
industry_mapping = lb_ind.classes_.tolist()
print(industry_mapping)

['Automotive', 'E-commerce', 'Education', 'Finance', 'Healthcare', 'Retail', 'Tech']

In [62]:
row_1 = dataset.iloc[1]
print(f"Industry 1st row:{row_1['industry_array']}")

Industry 1st row:[0, 0, 0, 0, 0, 0, 1]

* for employment_type

In [64]:
dataset.value_counts("employment_type")

employment_type
Internship    574
Full-time     509
Contract      465
Remote        452
Name: count, dtype: int64

In [65]:
lb_emp = LabelBinarizer()
emp_matrix = lb_emp.fit_transform(dataset['employment_type'])
dataset['employment_array'] = emp_matrix.tolist()

In [66]:
employment_mapping = lb_emp.classes_.tolist()
print(employment_mapping)

['Contract', 'Full-time', 'Internship', 'Remote']

In [67]:
row_1 = dataset.iloc[1]
print(f"Employment Type Array:{row_1['employment_array']}")

Employment Type Array:[0, 1, 0, 0]

* for company_size column

In [69]:
dataset.value_counts("company_size")

company_size
Startup    672
Mid        671
Large      657
Name: count, dtype: int64

In [70]:
lb_size = LabelBinarizer()
size_matrix = lb_size.fit_transform(dataset['company_size'])
dataset['size_array'] = size_matrix.tolist()

In [71]:
size_mapping = lb_size.classes_.tolist()
print(size_mapping)

['Large', 'Mid', 'Startup']

In [72]:
row_1 = dataset.iloc[1]
print(f"Company Size Array:{row_1['size_array']}")

Company Size Array:[1, 0, 0]

In [73]:
X_skills = np.stack(dataset['skills_array'].values)
X_exp = np.stack(dataset['experience_array'].values)
X_ind = np.stack(dataset['industry_array'].values)
X_emp = np.stack(dataset['employment_array'].values)
X_size = np.stack(dataset['size_array'].values)

In [74]:
X = np.hstack((X_skills, X_exp, X_ind, X_emp, X_size))
print(f"Final Input Matrix Shape: {X.shape}")

Final Input Matrix Shape: (2000, 39)

In [75]:
le_job = LabelEncoder()
y = le_job.fit_transform(dataset['job_title'])

In [76]:
job_mapping = le_job.classes_.tolist()
print(f"const JOB_TITLES = {job_mapping};")

const JOB_TITLES = ['AI Product Manager', 'AI Researcher', 'Computer Vision Engineer', 'Data Analyst', 'Data Scientist', 'ML Engineer', 'NLP Engineer', 'Quant Researcher'];